### ISSUE TITLE
Include instruction to run it locally

### ISSUE THREAD

**Issue by SamGuay** [brainhackorg/brainhack_jupyter_book#1]
So happy to see the _paper_ take form! :rocket: 

I think it would be great to have some a nice README.md with the instruction on how to deploy the book locally so folks can also play with it. 

I like how [The Turing Way](https://github.com/alan-turing-institute/the-turing-way/tree/master/book) folks have done it, and I'm sure it can easily be adapted for our purpose.

**Comment by complexbrains** [comment]
I started a [README.md](https://hackmd.io/VLt2DImnTWa8HQaMD7_OcQ) get going based on The Turing Way's and some other samples I found. Since I was not keen on the technical bits, I guess it requires your attention for sure, but I will work on the rest of the content and will make it more user-friendly.  Do you think would it be a starting point?

**Comment by htwangtw** [comment]
I have been doing a lot of local builds to test my edits - here are some relevant points from the top of my head. If someone can turn that into more user friendly content that will be super helpful.

---

1. create an virtual environment in your local copy and install related libraries with conda
```
conda env create -f environment.yml --prefix ./envs
```
Always activate this enviornment when you want to run stuff
```
conda activate ./envs
```
I use `virtualenv` but currently we don't have requirement file for pip in this repo.
Shall we add a `requirements.txt` (or recover from the earlier version) to give people options? 

2. build the content in the repository locally
```bash
jupyter-book build brainhack_book
```
or use stuff in `Makefile`: 
```bash
make book
```
3. compile pages that need markdown tables

Some information is generated from spreadsheets in `data` or files downloaded from osf during the website building process. Currently they are the acknowledgements and contributors pages.
Spreadsheets for acknowledgements is stored in `data` but the contributor list is on osf.
Download contributor list from osf:
```bash
make contributors
```
Build the pages with markdown table:
```bash
python brainhack_jupyter_book/mdtable.py [see options in the script]
```
or use stuff in `Makefile`: 
```bash
make preprint  # preprint related pages
make bookpage  # jupyter book related pages
```
4. cleaning your local directory 
There's a make command to sweap all the files related to the local build that are not needed in the repo:
```bash
make clean
```

**Comment by Remi-Gau** [comment]
@complexbrains I think you should open a PR with the content of the hackmd you linked to.

I would even be tempted to merge right away as is.

It would give us a starting point from which to iterate.

Then we could thing of how to divide this content in between a README (what is this project?) and into CONTRIBUTING (with a section on what to contribute, how to contribute, how to run locally) where we could then add @htwangtw "make" suggestions from above.

**Comment by anibalsolon** [comment]
+1 to add a `requirements.txt`

**Comment by complexbrains** [comment]
Perfect! I am on it then. 

I will also add some bits and pieces to requirements and create an MD for it too and make my PR then! Thank you all!

**Comment by complexbrains** [comment]
Go for it then @htwangtw  I was pulling it from my own book so will go with yours then 🤗

**Comment by htwangtw** [comment]
Done and done!
