### ISSUE TITLE
Contributors page (for preprint submission)

### ISSUE THREAD

**Issue by shawnrhoads** [brainhackorg/brainhack_jupyter_book#10]
The Jupyter Book should feature a contributors page containing a table with authorship information (read from a .csv file).

**Comment by htwangtw** [comment]
I have written a basic markdown table generator, see PR #14.
The contributor table might need a bit more tweaking.
 It is going to be a wider table, I will have an update once I have a draft version.

**Comment by htwangtw** [comment]
![image](https://user-images.githubusercontent.com/13743617/105642388-4ec11180-5e81-11eb-83b9-3a752cbc06eb.png)

Here's a corner of the output from my markdown table generator with the contributor info spreadsheet from @Remi-Gau. 
The headers can be a bit long, and the table is really wide. I am thinking of collasping some information such as name and affiliations for the online version.

Another idea is to have three subpages and split the table into three - affiliation and contacts, events related contribution, paper contributions and the rest. However I am not confident to write a good info parser before the preprint day.

Any suggestions on how to approach this?

**Comment by Remi-Gau** [comment]
Am tempted to say that we can drop the affiliation 2 and 3

**Comment by htwangtw** [comment]
Yeah that would be an easy solution for the upcoming preprint.

**Comment by htwangtw** [comment]
I have created PR #20 for people to have a look @Remi-Gau 
It might be easier to build the book locally to have a better idea.

**Comment by htwangtw** [comment]
Resolved by PR #20
