### ISSUE TITLE
Glossary page (for preprint submission)

### ISSUE THREAD

**Issue by shawnrhoads** [brainhackorg/brainhack_jupyter_book#11]
Continue adding content to the Jupyter Book glossary, which will be referenced in the manuscript.

**Comment by vborghe** [comment]
@complexbrains (and everyone else!) what do you think if we do most of the typing [here](https://docs.google.com/document/d/1tksdcak_WasYs_wF3VRULJDzJz550hg4KA3xJY6B1kM/edit?usp=sharing) - so it is very accessible and comments/additions are fast - then we copy&paste&PR once in a while (i.e. for substantial changes)?

I am starting by making sure all the terms referred to in the manuscript are there 😅

**Comment by complexbrains** [comment]
Sure dear @vborghe whatever makes it easier for anyone to contribute indeed. Actually I also started with a doc later converted it to the md. I also went over all the long 1st draft carefully to make sure we do not miss any words but now it is easier given the page number hopefully we should be covering many terminologies but some might have added I was not aware of. 

Please let me know if I can help with anything. Thank you for leading the effort with Yasmine 🤗

**Comment by vborghe** [comment]
Closed by #21 - which covers all terms for the preprint - further changes can be made via PR/issues
