### ISSUE TITLE
Updating English Glossary with Missing Terms

### ISSUE THREAD

**Issue by licataae** [brainhackorg/brainhack_jupyter_book#121]
Updating the Brainhack Book Glossary (English) by adding in all missing terms & ordering alphabetically. The updated glossary is here: https://docs.google.com/document/d/1K_8P_u2th7JGtxpHli33VBqUgeTFBRtAEI3mGOZhRJ0/edit

- [X] I read and understood the project description.
- [X] I read and understood the workflow & contribution guidelines
- [X] Missing terms have been added
- [X] Missing terms have been proofread
- [X] Reviews from (at least) two native speakers have been requested (link reviewer names/profiles): Lucy Mohrhauer, Patrick Callahan
- [X] Reviews from two native speakers have been incorporated into the glossary
- [ ] Completed, proofread and reviewed glossary has been merged to the main branch via PR

**Comment by Remi-Gau** [comment]
Wow. This is awesome!

Do you want to open a pull request to update this file with the new content: https://github.com/brainhackorg/brainhack_jupyter_book/blob/main/brainhack_book/glossary_en.md ?

**Comment by licataae** [comment]
Sure thing ! Just opened a PR.

**Comment by Remi-Gau** [comment]
@licataae 

do Lucy Mohrhauer and Patrick Callahan have github account? 

why: trying to keep track of contributors ?

**Comment by Remi-Gau** [comment]
ok thanks
either way I now know either where to find it if it exists or not to look for it
