### ISSUE TITLE
Fix deploy-book action

### ISSUE THREAD

**Issue by shawnrhoads** [brainhackorg/brainhack_jupyter_book#15]
The github action `deploy-book` times out / no longer builds the Jupyter Book upon merging to `main`.

Looks like timing out first occurred after [the commit adding the issue templates](https://github.com/brainhackorg/brainhack_jupyter_book/commit/2210fc66f3b3d5fd1ee690ab794798844eaf7506) under `.github/ISSUE_TEMPLATE/`. However, it doesn't make sense that adding the templates would be cause of the issue.

Upon investigating the cause, looks like it has more to do with installing dependencies under the workflow (see [action](https://github.com/brainhackorg/brainhack_jupyter_book/runs/1752266430?check_suite_focus=true)).

Any thoughts on switching to a Miniconda solution to build the book? Might be more stable in the long-run. Here's [an example](https://github.com/shawnrhoads/gu-psyc-347/blob/master/.github/workflows/deploy-book.yml) of what a Miniconda solution could look like.

**Comment by PeerHerholz** [comment]
Hi @shawnrhoads,

yeah, I was about to propose the same. IIRC `pip` changed the way things are resolved upon installing/downloading stuff. 
Definitely +1 from my side!

**Comment by shawnrhoads** [comment]
Cool, I can likely put something together if you think it would be helpful! Feel free to assign me if so!

**Comment by PeerHerholz** [comment]
Done, merci!
