### ISSUE TITLE
Needing a contributor guideline?

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/brainhack_jupyter_book#2]
If this is needed I will start a draft going while we work on the content based on the [Turing way's contribution guideline](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#referencing-and-citing) and some others. So I will assign it to myself, anyone who wants to help (I believe I will need help for the technical aspects) more than welcomed.

**Comment by complexbrains** [comment]
I opened an issue in the Turing Way's repo for asking/letting them know regarding the use of the Contribution Guidelines of theirs which is [here](https://github.com/alan-turing-institute/the-turing-way/issues/1737) and haven't heard back. If you all think it is alright to go for it and modify we can start working on that immediately. 

What do you think @Remi-Gau @SamGuay @yasminebassil @PeerHerholz @htwangtw ? 

I was also thinking to add some instructions regarding setting up the environment at the local and saw similar was done by @htwangtw. Would it be ok to have them in the guideline dear @htwangtw?

**Comment by htwangtw** [comment]
It would be great to get explicit permission from the Turing Way. Their contribution is very extensive.
I think it will be useful to have a TLDR starter pack on the side.
Anything that can help new contributors to onboard quickly, like create a fork, local build, simple PR, etc would be nice. 
I am happy for you to take my stuff and possibly add some glitters. Mine reads pretty boring. I can help to review things if you need!

**Comment by complexbrains** [comment]
Perfect 🤗 

Actually, your idea is even better. So regarding starter pack then, what you would think of having something like this we developed with @PeerHerholz and @anibalsolon for [Freesurfer Recon-all BIDS App](https://docs.google.com/document/d/1xJ22Ekog7-BFB_3DqYMPsnFCfAtjoNWe4iEgcaDtoXc/edit?usp=sharing) which already covers a lot regarding git/github/forking and so on? Shall we tailor it to our purposes and merge with the Turing Way's as necessary? 

Let me know what do you think so we can start copying that one and let anyone know in the channel so they can contribute too 🤗

**Comment by SamGuay** [comment]
The _Turing Way's_ [LICENSE.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/LICENSE.md) is CC-BY and clearly states: 

> ## Process documents and data
> 
> All documentation and chapter materials in this repository are made available under the [Creative Commons Attribution license][cc-by-human].
> The following is a human-readable summary of (and not a substitute for) the [full legal text of the CC BY 4.0 license][cc-by-legal].
> 
> You are free:
> 
> * to **Share**---copy and redistribute the material in any medium or format
> * to **Adapt**---remix, transform, and build upon the material
> 
> for any purpose, even commercially.
> 
> The licensor cannot revoke these freedoms as long as you follow the license terms.
> 
> Under the following terms:
> 
> * **Attribution**---You must give appropriate credit (mentioning that your work is derived from work that is Copyright © The Turing Way Community and, where practical, linking to https://github.com/alan-turing-institute/the-turing-way), provide a [link to the license][cc-by-human], and indicate if changes were made.
>   You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> * **No additional restrictions**---You may not apply legal terms or technological measures that legally restrict others from doing
> anything the license permits.
>   
> With the understanding that:
> 
> * You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an
>   applicable exception or limitation.
> * No warranties are given. The license may not give you all of the permissions necessary for your intended use.
>   For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

That is the beauty of open licencing :)

**Comment by complexbrains** [comment]
Sure sure, but @Remi-Gau and I was just thinking it is nice to let them know that we are looking up to their structure and would like to implement it. Just for the ecosystem itself and to show our respect and good will as always 🤗

**Comment by SamGuay** [comment]
Yesyes! I was just saying it in the case they don't reply in time before the preprint and the book are made _public_ to be on the safe side :).

**Comment by complexbrains** [comment]
[Here](https://docs.google.com/document/d/1IhMQSPZOBYOrJ1yd0_K0Uvd4vq0NyyZbknJav5DPArI/edit?usp=sharing) is the first initial draft I merged some bits from Turing Way's guideline and the other available ones. It is waiting care and help by you Jupyter book lovers and enthusiasts. Please help us with;

- [ ] Requires a nice introduction to be written
- [ ] Checking the links whether they are going to the right websites or not broken.
- [ ]  Check whether the technical details and references in the guideline are still up to date.
- [ ] Deciding on the issue labellings.
- [ ] Decide on issue types and templates accordingly.
- [ ] Decide on the PR template and issue in the guideline accordingly.
- [ ] Implementing technical info regarding creating jupyter book environment at the user end @htwangtw already had some details, they can be added with more/less details as needed.
- [ ] [Code of conduct](https://github.com/brainhackorg/brainhack_jupyter_book/issues/3) to brought it is the final version and to be linked.
- [ ] Decide on Pull request workflow and update the doc.

Will share this issue in the general Mattermost channel to ask for contributions. 🤗
