### ISSUE TITLE
Code of Conduct for the Book

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/brainhack_jupyter_book#3]
I believe again we will need something to get going. I am guessing the [CoC](https://hackmd.io/A97k1-9TRnqq0TfoFMtKUA) @anibalsolon created for Freesurfer BIDS-Apps should be a good starting point and we can develop more on that as necessary. I am self assigning myself again and pinging @SamGuay if he wants to add more to that from the [CoC](https://docs.google.com/document/d/11aE6vv67i9pzOUN7DTypqiAVUutXAijP7_jZTURHhAM/edit) we developed for Brainhack.

**Comment by htwangtw** [comment]
We have a guideline now - let's consider this one is closed. Still, advice is welcome!
