### ISSUE TITLE
Glossary: unconference

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/brainhack_jupyter_book#6]
In case this helps adding some definitions

Taken from the Craddock 2016 paper that already includes some terms.

> Sessions for attendees to present their research or other topics of current interest. Immediately prior to these sessions, the agenda is determined on-site. Attendees who are willing to present add their name to a sign-up sheet and in the event that there are more interested presenters than time, the group is polled to determine which presentations are given time or to extend the amount of time allotted. Instead of unconference sessions, some sites have incorporated ‘data blitzes,’ consisting of a pre-organized session where attendees have the opportunity to present their research. Brainhack Miami has had success with this model and has secured funding to award monetary prizes to the best presentations.

**Comment by vborghe** [comment]
'cause of #11 (and note taken [here](https://docs.google.com/document/d/1tksdcak_WasYs_wF3VRULJDzJz550hg4KA3xJY6B1kM/edit))
