### ISSUE TITLE
The Brainbox website insecure lead to test failed

### ISSUE THREAD

**Issue by htwangtw** [brainhackorg/brainhack_jupyter_book#64]
The Jupyter Book test fails because the Brainbox website is insecure on 16th of March, locally and on GitHub action (see PR #61). 
This is likely an external issue as book deployment a week ago was fine and I did not change any related code in that part. 
And the test _did_ pass, see: https://github.com/brainhackorg/brainhack_jupyter_book/runs/2071881691#step:5:62

We might want to consider deploying the book manually until it's fixed or make an exception?

**Comment by anibalsolon** [comment]
The exception is fine.

**Comment by katjaq** [comment]
👀  Thank you @anibalsolon 
Was there some more information? Did you see what is insecure @htwangtw @anibalsolon ? (BrainBox runs on https, so it would be nice to know more. Thank you both very much :)

**Comment by htwangtw** [comment]
@katjaq the error code is `SEC_ERROR_EXPIRED_CERTIFICATE`

```
https://brainbox.pasteur.fr/

Peer's Certificate has expired.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false
```

![image](https://user-images.githubusercontent.com/13743617/111439389-3c36bc00-86fd-11eb-8c75-a69e35bf48a8.png)
I hit the jackpot :tada:

**Comment by katjaq** [comment]
ha! Thank you! Yeees, we have to renew the certificate every now and then (which became much more frequent recently... 🙈) So – yeyy, you were the first to find!! :D Pinging @r03ert0  😊 oopsi!

Thank you @htwangtw ! should be good in a second :)

**Comment by katjaq** [comment]
fixed \\\ö// certificate renewed, should not throw error anymore even without exception :D

(but to be on the safe side, you could maybe leave the exception ? 🙈 – knowing us, we are often reminded once the certificate is expired 😬 we usually catch this within a few hours (as we use our tools on almost daily basis or collaborators ping us) but if folks were to compile the jupy book within this very hour, they may get this error message again and may be uncertain what to do. I just made a recurrent calendar entry every 3 months so hopefully we will catch it in time from now on... you decide 🙃 )

Thanks again for the ping! ❤️

**Comment by htwangtw** [comment]
Totally agree we should make it an exception. I will look into how to do so tomorrow, if no one fix this before me :wink:

**Comment by htwangtw** [comment]
This issue also happens with OSF links sometimes - will think about how to adapt that in the test.
