### ISSUE TITLE
Changes to be made on the proof

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/brainhack_jupyter_book#69]
- make sure that the consortium authorship has been sorted appropriately
- affiliations are probably going to be a headache

## Name changes

- [x]  "Visconti di Oleggio Castello" and not "Visconti di Oleggio"

## Figure

- [x] upload new figure

From Daniel M.

>very minor historical issue that would be nice to correct if the proofs aren't yet finalized. In the timeline, the 'First OHBM Brainhack' in 2013 wasn't actually a 'Brainhack'. It was organized by Nolan Nichols and JB Poline (and others), and was called the OHBM Hackathon. There wasn't any relation at that stage to Brainhack or the folks organizing the early Brainhacks. (The following year we did join forces to organize the 'OHBM Hackathon' in Berlin, and though we didn't use the term 'Brainhack' there either, it was arguably much more of the Brainhack variety due to the folks involved in organizing.) Nolan left the field a few years back, and the only other person who might notice this would be JB. Obviously this isn't a big issue if it can't be corrected, but I thought it better to say something if there's a chance to avoid rewriting history (in a very small way). The easiest fix for accuracy might be either to remove it or call it the "First OHBM Hackathon" — though including it in the Brainhack timeline does seem a bit misleading, but at least it wouldn't be mislabeled as something credited to Brainhack.
>
>(I found a links online to the original mentions of the OHBM 2013 and 2014 Hackathons as evidence I'm not completely losing my memory: https://www.humanbrainmapping.org/i4a/forms/index.cfm?id=40 , https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageID=3613&activateFull=true . It seems the names started to get mixed around 2018, which is also the first OHBM Hackathon that was organized by the new round of leadership from the open science SIG. My guess is that not knowing the history of these two events being separate, the terms got mixed, and the rest is history.)
>
>If this causes any trouble with Neuron, feel free to ignore it — and maybe we can just update the figure on the github website some day in the future.

**Comment by htwangtw** [comment]
Name change and resorting to the order is going to be easy. I can do that later today. 
For the affiliation, we might just need a lot of people to proofread it, unless we can just pass `data/contributors/neuroview/manscript_affiliation.tsv` to the copy editors and instruction for author arrange...

**Comment by htwangtw** [comment]
Visconti di Oleggio Castello - name is corrected now, see #70

**Comment by mvdoc** [comment]
- thanks for fixing my last name
- I fixed two rows on the google spreadsheet with the affiliations `s/Berkley/Berkeley` (sneaky `e`)
- the in-text citation for Cameron's paper reads `Cameron Craddock et al., 2006` instead of `Craddock et al., 2006`
- the in-text braindr's website could be probably changed to https://braindr.us (instead of https://braindr.us/#/)
- on page 6, the brackets around the links could be probably removed "Sharing(COBIDAS guidelines for MRI [http://www.humanbrainmapping.org/files/2016/COBIDASreport.pdf] as well as for EEG and MEG [https://osf.io/a8dhx/]"
- page 6, Neuromatch academy paper: that should be a citation to the eLife article instead of a link? now it reads  "Neuromatch Academy (https://elifesciences.org/articles/57892)"

**Comment by PeerHerholz** [comment]
The affiliation for @emdupre (line 118), @koudyk (line 241), @jbpoline (line 105), and myself (line 171) was updated in the spreadsheet.

**Comment by yeoyeo02** [comment]
I have updated my name on the spreadsheet. First name should be "B.T. Thomas". Thomas should not be in the middle, else it typically get abbreviated to just "T" in the final article. My apologies for the inconvenience.

**Comment by likeajumprope** [comment]
I have updated my affiliation in the spread sheet to "Centre for Youth Mental Health" and added my middle initials "M.M." 
I am #94 Johanna Bayer

**Comment by htwangtw** [comment]
Thank you all @PeerHerholz @mvdoc @likeajumprope @yeoyeo02!!! 
Much appriciated!!

**Comment by Remi-Gau** [comment]
- [ ]  add grant declaration

**Comment by katjaq** [comment]
Thank you so much all! 
I updated affiliation order of katja heuer (if that causes trouble, happy to change it back)
and i updated affiliation of katja, roberto toro, and nicolas traut --> ("University of Paris" is now the name for what was once 2 different universities before merge)

and I added our grant information to the second spreadsheet :)

Thank you <3 🚀

**Comment by SWideman** [comment]
Sorry, just added new Issue 71 instead of updating this one.
(Six minor cosmetic errors detailed there). 

**Great job**, everyone!  Thanks for the opportunity, hard work and above all - active participation!

**Comment by schw4b** [comment]
Thank's everyone for this large collaborative effort! Was a pleasure the read the proofs, looking great!

**Comment by Remi-Gau** [comment]
>     * the in-text citation for Cameron's paper reads `Cameron Craddock et al., 2006` instead of `Craddock et al., 2006`

@mvdoc 
That's actually how it is referenced in pubmed so I won't change it.
https://pubmed.ncbi.nlm.nih.gov/27042293/

**Comment by Remi-Gau** [comment]
>     * i updated affiliation of katja, roberto toro, and nicolas traut --> ("University of Paris" is now the name for what was once 2 different universities before merge)

There was an extra acronym in Roberto's affiliation. Removed it in the google spreadsheet. Pinging @htwangtw just to let you know. 
This is not urgent as the affiliation of the core members have to changed manually in the proofs anyway.

**Comment by Remi-Gau** [comment]
>     * on page 6, the brackets around the links could be probably removed "Sharing(COBIDAS guidelines for MRI [http://www.humanbrainmapping.org/files/2016/COBIDASreport.pdf] as well as for EEG and MEG [https://osf.io/a8dhx/]"

I am actually going to keep them as we have a brackets within brackets situation . :-)

**Comment by Remi-Gau** [comment]
>     * page 6, Neuromatch academy paper: that should be a citation to the eLife article instead of a link? now it reads  "Neuromatch Academy (https://elifesciences.org/articles/57892)"

@mvdoc I wonder if this was not done in order to avoid the reference count.

But actually would it not make sense to point to the Neuromatch academy preprint, rather than the Point for neuromatch ?

https://arxiv.org/abs/2012.08973

@SNeuroble

**Comment by Remi-Gau** [comment]
all boxesare ticked. closing

**Comment by SNeuroble** [comment]
> > ```
> > * page 6, Neuromatch academy paper: that should be a citation to the eLife article instead of a link? now it reads  "Neuromatch Academy (https://elifesciences.org/articles/57892)"
> > ```
> 
> @mvdoc I wonder if this was not done in order to avoid the reference count.
> 
> But actually would it not make sense to point to the Neuromatch academy preprint, rather than the Point for neuromatch ?


I know this is closed but just for the record:
Yup, this was chosen to be a link instead of citation to meet our reference limit (several other papers are referenced in this way in the manuscript).
And yes, the preprint makes more sense than the Point.
So the plan is to update the link—thanks for pointing this out @mvdoc!

**Comment by htwangtw** [comment]
I will mark this issue as closed as we all know the paper is there! :100:
