### ISSUE TITLE
Landing page (for preprint submission)

### ISSUE THREAD

**Issue by shawnrhoads** [brainhackorg/brainhack_jupyter_book#8]
The Jupyter Book should feature a landing page containing the figures and information about the manuscript and Jupyter Book.

**Comment by katjaq** [comment]
Hey! Thanks for creating this issue and adding info on what is needed @shawnrhoads ✨ 
We'll try to address it asap :)

**Comment by katjaq** [comment]
We are getting closer! :D  Just letting you know that we do plan to submit PR today (Thursday) with @anibalsolon and @yasminebassil :) \\\ö//

**Comment by katjaq** [comment]
yeyyy, we just pushed PR #29 :D and tagged you #15 

hope it finds you well! 😃
