### ISSUE TITLE
Admin: drop number of reviewer from 3 to 2

### ISSUE THREAD

**Issue by htwangtw** [brainhackorg/brainhack_jupyter_book#80]
@likeajumprope and I had a chat and was wondering if it would be a good idea to drop the number of reviews need from 3 to 2.

From past experience, PRs get staggered by waiting for reviewers. The jupyterbook PR doesn't always require super technical code review. I am not sure who has the admin right to change this. Would love to hear what people think. 

Tag people that might have more power than me on this repo:
@jhlegarreta @PeerHerholz @SamGuay @shawnrhoads

**Comment by jhlegarreta** [comment]
Switching to 2 sounds reasonable to me.

**Comment by shawnrhoads** [comment]
Also sounds fine to me!

If we still want some additional cushion before merging, I think we can also require "[status checks](https://docs.github.com/en/rest/reference/repos#statuses)" to pass before merging.

**Comment by htwangtw** [comment]
Right now we have some very basic check on if the links are alive. If there's more checks people wants to add that would be great!

**Comment by SamGuay** [comment]
I am all fine with 2 reviewers as well!

**Comment by SamGuay** [comment]
I didn't know I had such power for this repo. I have set the numbers of reviews to 2 and required the "status checks".

**Comment by htwangtw** [comment]
Finally I know who is our overlord
