### ISSUE TITLE
Acknowledgements page (for preprint submission)

### ISSUE THREAD

**Issue by shawnrhoads** [brainhackorg/brainhack_jupyter_book#9]
The Jupyter Book should feature an acknowledgments page containing information about Brainhack event sponsors (read from a .csv file).

**Comment by katjaq** [comment]
Thanks so much for setting this up so nicely @shawnrhoads and for taking a lead on that huge work together @htwangtw ✨ this is awesome! One thought (sorry I didn't think of that earlier: The current structure of the acknowledgements is first 1 paragraph of text which should remain this paragraph of text (no table); then second paragraph  
"These include (in alphabetical order):"  
and this is where @Remi-Gau had the nice idea to make a table from that alphabetic list. 

Do you think the 2 part structure will be okay for you to do? That would be awesome 🚀  Thanks so much for all your help! \\\ö//

**Comment by shawnrhoads** [comment]
Re adding the first paragraph: Sounds great @katjaq! (I guess minus the sentence about the Jupyter Book though). How about this?

> ~~The present manuscript is part of a growing community effort to collate BrainHack related insights and expertise into a Jupyter Book that will serve as a centralized set of resources for the community; w~~ We acknowledge all the individuals who contributed and will make ongoing contributions to these resources. Moreover, we would like to acknowledge all Brainhack organizers, supporters, presenters, and participants for their contribution to growing and maintaining this community. The benefits described in this manuscript would not be possible without them. We also thank all institutions, labs, and organisations who have helped this community grow, meet in stimulating environments, and add an excellent educational resource pool and agenda. With an expanding community, Brainhack’s support network keeps growing and we thank all labs and individual researchers for their dedication and expertise offered to this community.


Re table: I've written a script to organize the list of acknowledgments into an [acknowledgments.csv file](https://github.com/shawnrhoads/brainhack_jupyter_book/blob/update-acknowledgments/data/acknowledgments.csv) with two columns. Right now the columns are: ['Sponsor', 'Brainhack Event'] (but can be changed).

@htwangtw is writing something to read the authorship contributions table onto a Jupyter Notebook page (#10) and will then apply a similar approach using the acknowledgments.csv file. 

If this sounds good, I will submit a PR on a branch called `update-acknowledgments` adding this acknowledgments.csv file, then @htwangtw can edit that branch. 

What do you all think?

**Comment by katjaq** [comment]
good point :D 

Yes, but if the first sentence goes away, "to these resources" does not have a relation anymore. It could be formulated as "to the resources included in this Jupyter book." or "to the insights and resources included in this Jupyter book." or something else :) 
otherwise, green light for the PR from my side. :)

woowww! you guys ✨ 🚀  Fantastic! Thanks again !

**Comment by shawnrhoads** [comment]
Great! 

@htwangtw Do you want me to add an initial .md or .ipynb file with those edits to the first paragraph and a Markdown-style table that contains the info (only doesn't read it from a .csv file yet) for the time being? Alternatively, I can just add the acknowledgments.csv file. Let me know what will make your part easiest! 😄

**Comment by htwangtw** [comment]
Congrats on moving so fast on sorting out the acknowledgements!!! Add the data will be enough for now 🙂

**Comment by shawnrhoads** [comment]
Submitted a PR (#12) with the data!

Didn't add the code, but for future reference/reproducibility: I used the `pandas` and `re` packages in Python to split the original list (with entries separated by newlines) into two columns using regex pattern matching.

```
import pandas as pd, re

df = pd.read_csv('input_list.csv')
s = pd.Series(df['Sponsor'])

df['Sponsor'] = s.apply(lambda st: re.findall(r'^(.*?)\s\(', st)[0])
df['Brainhack Event'] = s.apply(lambda st: re.findall(r'\(.*\)', st)[0])

df.to_csv('acknowledgements.csv', index=False)
```

Then, I just reviewed to edit out any extra spaces/brackets that might have been in the list (I also added these revisions to the [manuscript](https://docs.google.com/document/d/1Fxvnqcod08CvGat8MxxvptuxBIFRZrnXBUUaMm_cBew/edit#), which now appear to have been accepted) and fix the special characters that didn't correctly write to csv correctly (might need an additional eye for this).

**Comment by htwangtw** [comment]
See PR (#14) for the current basic acknowledgements page and the markdown table parser!
I would like some feedback to see if the formatting of the table is okay.

**Comment by Remi-Gau** [comment]
My. I might finally learn some python.

**Comment by htwangtw** [comment]
I mostly want to know if the markdown output is sufficiently pretty. No pressure for anything else @Remi-Gau

**Comment by htwangtw** [comment]
PR #14 merged
